apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-configs-repo
  namespace: flux
spec:
  interval: 2m
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/weiyuanke/cluster-configs.git
