---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: apps
    namespace: flux
spec:
    prune: true
    path: "./clusters/myhome/apps"
    sourceRef:
        kind: GitRepository
        namespace: flux
        name: cluster-configs-repo
    validation: client
    interval: 5m
