apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-stack-charts.yaml
  - release.yaml
  - slo-pod-create.yaml
  - lb-svc.yaml
  - resourcestatetransition-pod.yaml
  - watchslo-config.yaml
