apiVersion: slo.kube-stack.me/v1beta1
kind: WatchSLO
metadata:
  name: watchslo-config
  namespace: kube-system
spec:
  configs:
  - selector:
      apiVersion: v1
      kind: Pod
    targetResource: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: kube-stack-target-pod
        namespace: kube-system
        labels:
          app: ubuntu
      spec:
        containers:
        - name: main
          image: docker.m.daocloud.io/library/ubuntu:22.04
          command:
          - sleep
          - infinity
  - selector:
      apiVersion: v1
      kind: Service
  - selector:
      apiVersion: v1
      kind: PersistentVolumeClaim
